### ISSUE TITLE
Installation problems?

### ISSUE THREAD

**Issue by jloveric** [crim-ca/brat-frontend-editor#25]
I'm trying to install with Node v10.0.0 and npm v6.1.1 and seeing build errors.  Not sure if anyone else sees this 

  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc:131:56: error: no matching member function for call to 'NewInstance'
        Local<Object> wrapper = Nan::New(constructor)->NewInstance();

etc...

**Comment by Renaud009** [comment]
Just removed some useless jquery packages from dependencies. 
Should now have no error after an install with node 10.
The package that depended on contextify wasn't used tho, so you could have just ignored the error or use "--no-optional" flag when installing.
